# Basic
title: 小小球员
subtitle: Know a little about a lot, know a lot about a little.
welcome_message: 编程·足球·摄影·读书
description: Hi~ 我是小小球员，一名 iOS 开发者。
#creator: <a href="http://xxqy.fun">@小小球员</a>

url: "http://xxqy123.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: lightblue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/xxqy123?tab=repositories'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: xxqy
    # duoshuo: 
    
# Social
social:
    weibo: 2151297884
    github: xxqy123
    twitter: little_playeer
 #   gplus: 111
    mail: xqy0609@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
